name: Studio Deploy Development
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Caching
        id: react-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-react-studio-dappify-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-react-studio-dappify-
      - name: Install dependencies
        run: yarn install
      - name: Build
        env: 
          REACT_APP_MORALIS_APP_ID: ${{ secrets.MORALIS_APP_ID_DEV }}
          REACT_APP_MORALIS_SERVER_URL: ${{ secrets.MORALIS_SERVER_URL_DEV }}
          REACT_APP_HOST_ENV: dev
          CI: false
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: yarn build:cli
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: yarn deploy:development